[unstable]
profile-rustflags = true
codegen-backend = true

[profile.dev]
incremental = true
opt-level = 0
codegen-backend = "cranelift"
rustflags = [
	"-Zthreads=0", #num cores
	"-Zshare-generics=y",
	"-Cprefer-dynamic"
]

# This applies to proc macros, which are executed during build, but ought to be caught by below.
[profile.dev.build-override]
opt-level = 3

[profile.dev.package."*"]
incremental = false
codegen-backend = "llvm"
opt-level = 3
