
[profile.dev]
incremental = true
opt-level = 1
codegen-backend = "cranelift"
rustflags = ["-Z", "threads=8", "-Cprefer-dynamic"]

[profile.dev.package."*"]
incremental = false
opt-level = 3
codegen-backend = "llvm"

[target.x86_64-unknown-linux-gnu]
rustflags = [
  # (Nightly) Make the current crate share its generic instantiations
  "-Zshare-generics=y",
]

[unstable]
codegen-backend = true